spring.application.name: spring-ai-demo

spring.ai.model.chat: openai
spring.ai.model.embedding: zhipuai

spring.ai.openai:
  base-url: https://api.deepseek.com
  api-key: yours
  chat.options.model: deepseek-chat

spring.ai.zhipuai:
  api-key: yours
  embedding:
    options:
      model: embedding-2

spring.ai.vectorstore.pgvector:
  initialize-schema: true
  dimensions: 1024 #embedding-2 default


management.otlp.tracing.endpoint: http://localhost:4318/v1/traces #enable OtlpHttpSpanExporter
management.tracing.sampling.probability: 1.0 #always sampling for development

spring:
  ai:
    chat:
      observations:
        log-prompt: true
        log-completion: true
      client:
        observations:
          log-prompt: true
    vectorstore:
      observations:
        log-query-response: true