spring.application.name: spring-ai-demo

spring.ai.model.chat: openai
spring.ai.model.embedding: zhipuai

spring.ai.openai:
  base-url: https://api.deepseek.com
  api-key: yours
  chat.options.model: deepseek-chat

spring.ai.zhipuai:
  api-key: yours
  embedding:
    options:
      model: embedding-2

spring.ai.vectorstore.pgvector:
  initialize-schema: true
  dimensions: 1024 #embedding-2 default